<div class="lw_login_wrapper">

	
		<?php if ($this->notfound): ?>
			<div class="lw_login_error"><span>
		<?php if ($this->lang == "de"):?>
			Zum übermitteltem Code wurde keine Registrierung gefunden.
		<?php else: ?>
			No valid registration found for this code.
		<?php endif;?>
			</span></div>
		<?php endif; ?>
	
		
		<?php if ($this->success): ?>
			<div class="lw_login_success"><span>
		<?php if ($this->lang == "de"):?>
			Sie haben Ihr Passwort erfolgreich geändert. <a href="<?php echo $this->loginurl;?>">Sie können sich nun einloggen.</a>
		<?php else: ?>
			You have successfully changed your password. <a href="<?php echo $this->loginurl;?>">You may login now.</a>
		<?php endif;?>
			</span></div>
		<?php endif; ?>
		
		<?php if ($this->found&&!$this->error): ?>
			<div class="lw_login_message"><span>
		<?php if ($this->lang == "de"):?>
			Bitte geben Sie Ihr neues Passwort zweimal ein:
		<?php else: ?>
			Please enter your new password twice:
		<?php endif;?>
			</span></div>
		<?php endif; ?>
	
		<?php if ($this->showpassworddialog): ?>
		
		<form action="<?php echo $this->action; ?>" method="POST" autocomplete="on" class="lw_login_form">
		
		<?php if ($this->error): ?>
			<div class="lw_login_error"><span>
		<?php if ($this->lang == "de"):?>
			Fehler: Bitte achten Sie darauf, daß die Passwörter mindestens 5 Zeichen haben und gleich sind.
		<?php else: ?>
			Error: Please make sure that the passwords are 5 or more characters long and equal.
		<?php endif;?>
			</span></div>
		<?php endif; ?>
		
		<input type="hidden" name="password" value="1" />
		<div id="pwlost_email">
		
		
		
			<div class="lw_login_name_label">
				<?php if ($this->lang == "de"):?>
				<span>Ihr neues Passwort:</span>
				<?php else: ?>
				<span>Your new password:</span>
				<?php endif; ?>
			</div>
		
			<div class="lw_login_name_field">
				<input type="password" name="lw_login_pass_1" />
			</div>
			
			<div class="lw_login_name_label">
				<?php if ($this->lang == "de"):?>
					<span>Passwort Wiederholung:</span>
				<?php else: ?>
					<span>Repear password:</span>
				<?php endif; ?>
			</div>
		
			<div class="lw_login_name_field">
				<input type="password" name="lw_login_pass_2" />
			</div>
			

		</div>


		<div>
			<input id="lw_login_submit_button" onClick="document.location.href='<?php echo $this->backurl; ?>';" type="button" value="<?php if ($this->lang == "de"):?>zur&uuml;ck<?php else: ?>back<?php endif;?>" />
			<input id="lw_login_submit_button" type="submit" value="<?php if ($this->lang == "de"):?>absenden<?php else: ?>send<?php endif;?>" />
		</div>
		</form>
		
		<?php endif; ?>
		
		<?php if (!$this->showpassworddialog): ?>
		
			<?php if ($this->lang == "de"):?>
				<a href="<?php echo $this->backurl; ?>">zur&uuml;ck</a>
			<?php else: ?>
				<a href="<?php echo $this->backurl; ?>">back</a>
			<?php endif;?>
		
		<?php endif;?>
		

</div>